# Generated by Django 2.2 on 2019-04-26 17:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_auto_20171220_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedUserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='Name', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Note', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created', null=True)),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last updated', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.DictDocumentMixin),
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='user',
        ),
        migrations.AddField(
            model_name='scoreditem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Created', null=True),
        ),
        migrations.AddField(
            model_name='scoreditem',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Name', max_length=255),
        ),
        migrations.AddField(
            model_name='scoreditem',
            name='note',
            field=models.TextField(blank=True, help_text='Note', null=True),
        ),
        migrations.AddField(
            model_name='scoreditem',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Created', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated', null=True),
        ),
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('taggeduseritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.TaggedUserItem')),
                ('img', models.ImageField(upload_to=core.models.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.taggeduseritem',),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
