# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 14:20
from __future__ import unicode_literals

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Note', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Last updated')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.DictDocumentMixin),
        ),
        migrations.CreateModel(
            name='AsanaForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('pict', models.ImageField(height_field=100, help_text='Pictogram 100x100px', upload_to='asana/pict/', width_field=100)),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='asana.Asana')),
            ],
        ),
    ]
