# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 08:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanaform',
            name='pict_height',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='asanaform',
            name='pict_width',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='asanaform',
            name='pict',
            field=models.ImageField(height_field='pict_height', help_text='Pictogram 100x100px', upload_to='asana/pict/', width_field='pict_width'),
        ),
    ]
